### ISSUE TITLE
Feature request: Support config for URL_BASE

### ISSUE THREAD

**Issue by raliste** [Python-Markdown/github-links#7]
This could be useful for GitHub Enterprise setups (or even Gitlab).

The current workaround is:

```py
import mdx_gh_links

mdx_gh_links.URL_BASE = 'https://ghe.bigcorp.com'
        
m = markdown.markdown(
  some_input,
  extensions=[mdx_gh_links.GithubLinks()],
)
```

**Comment by waylan** [comment]
My initial reaction is to say that I'm not interested in supporting multiple different services. This is a GitHub only solution (as the name implies). If someone wants to fork this to support their service of choice or to build a general purpose (cross service) solution, that would be fine with me. Just make sure to shay within the licence terms. 

Of course, GitHub Enterprise is still GitHub. But if I add a setting for `URL_BASE` then people will inevitably try to use it for GitLab, Bitbucket, etc and I'm not interested in fielding bug reports due to minor idiosyncrasies between the various services.
